# This workflow will do a clean install of node dependencies, build the library, run testem visual tests for Firefox

name: Visual unit tests on Firefox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  firefox-visual-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests on Firefox
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build -- -f -x gestures,accessors
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: npm run test -- -s visual -p 8080 -c firefox
